// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import ()

type Board struct {
	BoardID int32
	Name    string
}

type Reply struct {
	ReplyID  int32
	Comment  string
	Date     string
	ThreadID int32
}

type Thread struct {
	ThreadID int32
	Title    string
	Comment  string
	Date     string
	BoardID  int32
}
